export const ActionTypes = {
    SET_EMPLOYEES: "SET_EMPLOYEES",
    SELECTED_EMPLOYEE: "SELECTED_EMPLOYEE",
    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    REMOVE_SELECTED_EMPLOYEE: "REMOVE_SELECTED_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    SET_DEPARTMENTS: 'SET_DEPARTMENTS',
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
};